version: '3.4'

services:
  todo-go-reactjs:
    image: ramosisw/todo-go-reactjs
    hostname: todo-go-reactjs
    container_name: todo-go-reactjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4080:80"
    volumes:
      - ./volumes/data/:/data/
